'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class GraphTester

    
    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    <System.ComponentModel.Description("form1 control.")> _
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    
    '''<summary>
    '''ListBox1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    <System.ComponentModel.Description("ListBox1 control.")> _
    Protected WithEvents ListBox1 As Global.System.Web.UI.WebControls.ListBox

    
    '''<summary>
    '''tbSqlStmt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    <System.ComponentModel.Description("tbSqlStmt control.")> _
    Protected WithEvents tbSqlStmt As Global.DTIMiniControls.HighlighedEditor

    
    '''<summary>
    '''tabs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    <System.ComponentModel.Description("tabs control.")> _
    Protected WithEvents tabs As Global.JqueryUIControls.Tabs

    
    '''<summary>
    '''btnRun control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    <System.ComponentModel.Description("btnRun control.")> _
    Protected WithEvents btnRun As Global.System.Web.UI.WebControls.Button

    
    '''<summary>
    '''ddTheme control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    <System.ComponentModel.Description("ddTheme control.")> _
    Protected WithEvents ddTheme As Global.System.Web.UI.WebControls.DropDownList
End Class
