'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ReportParms

    
    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    <System.ComponentModel.Description("form1 control.")> _
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    
    '''<summary>
    '''hidReportID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    <System.ComponentModel.Description("hidReportID control.")> _
    Protected WithEvents hidReportID As Global.System.Web.UI.WebControls.HiddenField

    
    '''<summary>
    '''tbReportName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    <System.ComponentModel.Description("tbReportName control.")> _
    Protected WithEvents tbReportName As Global.System.Web.UI.WebControls.Label

    
    '''<summary>
    '''btnAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    <System.ComponentModel.Description("btnAdd control.")> _
    Protected WithEvents btnAdd As Global.System.Web.UI.WebControls.Button

    
    '''<summary>
    '''btnRegen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    <System.ComponentModel.Description("btnRegen control.")> _
    Protected WithEvents btnRegen As Global.System.Web.UI.WebControls.Button

    
    '''<summary>
    '''repeater1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    <System.ComponentModel.Description("repeater1 control.")> _
    Protected WithEvents repeater1 As Global.System.Web.UI.WebControls.Repeater

    
    '''<summary>
    '''btnSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    <System.ComponentModel.Description("btnSave control.")> _
    Protected WithEvents btnSave As Global.System.Web.UI.WebControls.Button
End Class
